WIP: demo wordpress-microservice app
replicatedhq/platform-examples pull request #25
Opened 2024-12-29 21:05 UTC by 5hubh49

Build this wordpress app as part of a CRE task. This demo app consist of a frontend wordpress app, backend mariadb db and a custom metrics sidecar container named mysql-exporter.

2025-01-19 22:31 UTC, xavpaice requested changes
1. there's some commented sections that don't serve any purpose, I'd prefer to see them cleaned out.
2. I'd like Diamon to review the chart and patterns, but an idea for the future improvements is to have a database be available either as part of this application (embedded) or as a separate, external, db with values we need to fill in.  If the db is embedded, let's automate the password etc so folks don't need to fill it in, but can access that info later on.

2025-01-19 22:31 UTC, xavpaice commented on applications/wordpress-microservice/values.yaml
> +#    weeklyActiveUsers: 10
let's get rid of this commented section, it doesn't serve any purpose

2025-01-19 22:31 UTC, xavpaice commented on applications/wordpress-microservice/values.yaml
> +    MYSQL_PASSWORD: wordpress_password
this is a great opportunity to demonstrate to customers how they might embed the database in their application (in this case, use the mariadb image to deploy), or use an external db.  Depending on their choices, is how the wordpress env gets filled out.

2025-01-19 22:31 UTC, xavpaice commented on applications/wordpress-microservice/templates/wordpress-deployment.yaml
> +#            name: custom-metrics-config
this commented section can be removed

2025-01-19 22:31 UTC, xavpaice commented on applications/wordpress-microservice/templates/mariadb-deployment.yaml
> +#              name: metrics
this commented section can be removed

2025-01-23 03:50 UTC, 5hubh49 commented on applications/wordpress-microservice/templates/mariadb-deployment.yaml
> +#              name: metrics
done

2025-01-23 03:50 UTC, 5hubh49 commented on applications/wordpress-microservice/templates/wordpress-deployment.yaml
> +#            name: custom-metrics-config
done

2025-01-23 03:50 UTC, 5hubh49 commented on applications/wordpress-microservice/values.yaml
> +    MYSQL_PASSWORD: wordpress_password
noted!

2025-01-23 03:51 UTC, 5hubh49 commented on applications/wordpress-microservice/values.yaml
> +#    weeklyActiveUsers: 10
done

2025-01-23 15:13 UTC, diamonwiggins requested changes
Left you some feedback

2025-01-23 15:13 UTC, diamonwiggins commented on applications/wordpress-microservice/templates/wordpress-deployment.yaml
> +kind: Deployment
The same feedback i gave on the other Deployment objects applies here as well.

2025-01-23 15:13 UTC, diamonwiggins commented on applications/wordpress-microservice/values.yaml
> +  embedded: true  # Set to false to use an external database
I see you have the conditional for embedded vs. external but i don't see any option to provide a URI or an existing secret for connecting to that external database?

2025-02-02 21:42 UTC, 5hubh49 commented on applications/wordpress-microservice/Chart.yaml
> +  version: 1.0.0-beta.31
done

2025-02-03 11:32 UTC, 5hubh49 commented on applications/wordpress-microservice/templates/cronjob.yaml
> +              image: "{{ .Values.cronjob.image }}"
done

2025-02-03 11:32 UTC, 5hubh49 commented on applications/wordpress-microservice/templates/mariadb-deployment.yaml
> +          image: mariadb:10.5
done

2025-02-05 06:17 UTC, 5hubh49 commented on applications/wordpress-microservice/templates/secret.yaml
> +  root-password: {{ .Values.database.rootPassword | default (randAlphaNum 16) | b64enc }}
done

2025-02-07 12:05 UTC, 5hubh49 commented on applications/wordpress-microservice/values.yaml
> +  embedded: true  # Set to false to use an external database
Done. For external, db password should be set manually in `values.yaml` & has added the URI fields.

2025-02-09 20:56 UTC, 5hubh49 commented on applications/wordpress-microservice/templates/wordpress-service.yaml
> +    app: wordpress
done

2025-02-09 20:56 UTC, 5hubh49 commented on applications/wordpress-microservice/templates/mariadb-service.yaml
> +    app: mariadb
done

2025-02-09 21:06 UTC, 5hubh49 commented on applications/wordpress-microservice/manifests/wordpress-microservice.yaml
> +kind: HelmChart
added timeout & --wait flag

2025-02-10 12:21 UTC, 5hubh49 commented on applications/wordpress-microservice/templates/mariadb-deployment.yaml
> +kind: Deployment
done

2025-02-10 18:28 UTC, diamonwiggins requested changes
Looking good. Just a couple more things, and then we can get this merged in.

2025-02-10 18:28 UTC, diamonwiggins commented on applications/wordpress-microservice/templates/mariadb-deployment.yaml
> +       #{{- include "wordpress-microservice.selectorLabels" . | nindent 8 }}
consider cleaning up some of the parts that are commented out and no longer needed if possible. this confused me for a bit.

2025-02-10 18:28 UTC, diamonwiggins commented on applications/wordpress-microservice/templates/mariadb-deployment.yaml
> +      {{- end }}
A common pattern is to distinguish between security context at the pod level vs. the container level. 

Also, i'm not sure if you're allowing every possible option to be set which might cause you more work in the future. 

See how this is handled in Mlflow to get a better idea for how I've commonly seen this implemented - https://github.com/replicatedhq/platform-examples/blob/main/applications/mlflow/charts/mlflow/templates/deployment.yaml#L59-L62

You'll notice there is a `podSecurityContext` and `containerSecurityContext` value

2025-02-12 04:22 UTC, closed without merging